version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: src\WebApi\Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
